name: Code Catalyst

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        xcodebuild clean test -workspace iOS-Starter.xcodeproj/project.xcworkspace -scheme "iOS-Starter" -destination "platform=iOS Simulator,name=iPhone 12" -enableCodeCoverage YES
    - name: Generate Code Coverage Report
      run: |
        xcrun llvm-cov export -format="lcov" -instr-profile="$(pwd)/Derived Data/CodeCoverage/ProfileData/Coverage.profdata" "$(pwd)/Derived Data/CodeCoverage/Products/Debug/iOS-Starter.app/iOS-Starter" > coverage.lcov
    - uses: codecov/codecov-action@v1
      with:
        files: ./coverage.lcov
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
